const COSMETIC_CATALOG = {
  avatars: [
    { name: "thumbs", label: "Thumbs Icon Theme", price: 0 },
    { name: "adventurer", label: "Adventurer Icon Theme", price: 500 },
    { name: "adventurer-neutral", label: "Adventurer Neutral Icon Theme", price: 500 },
    { name: "avataaars", label: "Avataaars Icon Theme", price: 500 },
    { name: "avataaars-neutral", label: "Avataaars Neutral Icon Theme", price: 500 },
    { name: "big-ears", label: "Big Ears Icon Theme", price: 500 },
    { name: "big-ears-neutral", label: "Big Ears Neutral Icon Theme", price: 500 },
    { name: "big-smile", label: "Big Smile Icon Theme", price: 500 },
    { name: "bottts", label: "Bottts Icon Theme", price: 500 },
    { name: "bottts-neutral", label: "Bottts Neutral Icon Theme", price: 500 },
    { name: "croodles", label: "Croodles Icon Theme", price: 500 },
    { name: "croodles-neutral", label: "Croodles Neutral Icon Theme", price: 500 },
    { name: "dylan", label: "Dylan Icon Theme", price: 500 },
    { name: "fun-emoji", label: "Fun Emoji Icon Theme", price: 500 },
    { name: "glass", label: "Glass Icon Theme", price: 500 },
    { name: "icons", label: "Icons Icon Theme", price: 500 },
    { name: "identicon", label: "Identicon Icon Theme", price: 500 },
    { name: "initials", label: "Initials Icon Theme", price: 500 },
    { name: "lorelei", label: "Lorelei Icon Theme", price: 500 },
    { name: "lorelei-neutral", label: "Lorelei Neutral Icon Theme", price: 500 },
    { name: "micah", label: "Micah Icon Theme", price: 500 },
    { name: "miniavs", label: "Miniavs Icon Theme", price: 500 },
    { name: "notionists", label: "Notionists Icon Theme", price: 500 },
    { name: "notionists-neutral", label: "Notionists Neutral Icon Theme", price: 500 },
    { name: "open-peeps", label: "Open Peeps Icon Theme", price: 500 },
    { name: "personas", label: "Personas Icon Theme", price: 500 },
    { name: "pixel-art", label: "Pixel Art Icon Theme", price: 500 },
    { name: "pixel-art-neutral", label: "Pixel Art Neutral Icon Theme", price: 500 },
    { name: "rings", label: "Rings Icon Theme", price: 500 },
    { name: "shapes", label: "Shapes Icon Theme", price: 500 },
    { name: "toon-head", label: "Toon Head Icon Theme", price: 500 },
  ],
  borders: [
    { name: "None", label: "None", price: 0 },
    { name: "Neon", label: "Neon", price: 360 },
    { name: "Lava Pulse", label: "Lava Pulse", price: 540 },
    { name: "Royal Gold", label: "Royal Gold", price: 660 },
    { name: "Glitch", label: "Glitch", price: 780 },
    { name: "Anarchist", label: "Anarchist", price: 1080 },
    { name: "Circuit", label: "Circuit", price: 900 },
    { name: "Frost", label: "Frost", price: 960 },
    { name: "Candy Stripe", label: "Candy Stripe", price: 1020 },
    { name: "Void Rift", label: "Void Rift", price: 1180 },
    { name: "Emerald", label: "Emerald", price: 1260 },
  ],
  boardSkins: [
    { name: "Classic Chaos", label: "Classic Chaos", price: 0 },
    { name: "Lava Board", label: "Lava Board", price: 1400 },
    { name: "Midnight", label: "Midnight", price: 1650 },
    { name: "Candy Clash", label: "Candy Clash", price: 2000 },
    { name: "Arcade Grid", label: "Arcade Grid", price: 2260 },
    { name: "Royal Marble", label: "Royal Marble", price: 2500 },
    { name: "Forest Tactics", label: "Forest Tactics", price: 2100 },
    { name: "Frosted Glass", label: "Frosted Glass", price: 2380 },
    { name: "Desert Mirage", label: "Desert Mirage", price: 2440 },
    { name: "Cyber Circuit", label: "Cyber Circuit", price: 2680 },
    { name: "Monochrome", label: "Monochrome", price: 2820 },
  ],
  pieceSkins: [
    { name: "Standard", label: "Standard", price: 0 },
    { name: "Royal Glass", label: "Royal Glass", price: 1100 },
    { name: "Neon Plastic", label: "Neon Plastic", price: 1240 },
    { name: "Lava Stone", label: "Lava Stone", price: 1550 },
    { name: "Toy Army", label: "Toy Army", price: 1720 },
    { name: "Void Metal", label: "Void Metal", price: 2000 },
    { name: "Crystal Set", label: "Crystal Set", price: 1820 },
    { name: "Brass Engines", label: "Brass Engines", price: 1940 },
    { name: "Candy Pieces", label: "Candy Pieces", price: 2060 },
    { name: "Shadow Ink", label: "Shadow Ink", price: 2180 },
    { name: "Hologram", label: "Hologram", price: 2360 },
  ],
  emotes: [
    { name: "Good game", label: "Good game", price: 0 },
    { name: "Calculated", label: "Calculated", price: 240 },
    { name: "Oops", label: "Oops", price: 240 },
    { name: "Rule diff", label: "Rule diff", price: 360 },
    { name: "My queen was bait", label: "My queen was bait", price: 420 },
    { name: "Chaos approved", label: "Chaos approved", price: 540 },
    { name: "Your move", label: "Your move", price: 420 },
    { name: "Brilliant chaos", label: "Brilliant chaos", price: 520 },
    { name: "Not like this", label: "Not like this", price: 560 },
    { name: "Try that again", label: "Try that again", price: 620 },
    { name: "Check the rules", label: "Check the rules", price: 700 },
  ],
  banners: [
    { name: "Sunset Clash", label: "Sunset Clash", price: 0 },
    { name: "Rule Storm", label: "Rule Storm", price: 480 },
    { name: "Gold Table", label: "Gold Table", price: 660 },
    { name: "Lava Lounge", label: "Lava Lounge", price: 720 },
    { name: "Neon Boardwalk", label: "Neon Boardwalk", price: 780 },
    { name: "Grand Arena", label: "Grand Arena", price: 1020 },
    { name: "Aurora Field", label: "Aurora Field", price: 880 },
    { name: "Storm Front", label: "Storm Front", price: 940 },
    { name: "Crystal Hall", label: "Crystal Hall", price: 1040 },
    { name: "Verdant Crown", label: "Verdant Crown", price: 1120 },
    { name: "Void Horizon", label: "Void Horizon", price: 1280 },
  ],
  cardBacks: [
    { name: "Classic Cards", label: "Classic Cards", price: 0 },
    { name: "Lava Cards", label: "Lava Cards", price: 1000 },
    { name: "Gold Foil", label: "Gold Foil", price: 1200 },
    { name: "Static Noise", label: "Static Noise", price: 1450 },
    { name: "Nebula", label: "Nebula", price: 1320 },
    { name: "Circuit Board", label: "Circuit Board", price: 1380 },
    { name: "Frosted", label: "Frosted", price: 1500 },
    { name: "Candy Pop", label: "Candy Pop", price: 1560 },
    { name: "Emerald Felt", label: "Emerald Felt", price: 1680 },
  ],
};

const COSMETIC_PROFILE_FIELDS = {
  avatars: "avatar",
  borders: "border",
  boardSkins: "boardSkin",
  pieceSkins: "pieceSkin",
  emotes: "emote",
  banners: "banner",
  cardBacks: "cardBack",
};

module.exports = {
  COSMETIC_CATALOG,
  COSMETIC_PROFILE_FIELDS,
};
